#!/usr/bin/env python3
"""
Extract symbol glyphs from NF-Mono.ttf at the target font pixel sizes.
Uses larger variants: ▶ (U+25B6) instead of ▸, ▼ (U+25BC) instead of ▾.
"""

import freetype
import sys
import os

# (codepoint_to_render, target_codepoint_in_font, name, advance_override_28, advance_override_22)
# We render the "big" variant but store it under the "small" codepoint for matching
SYMBOLS = [
    (0x25B6, 0x25B8, "TRI_RIGHT", None, None),   # ▶→▸
    (0x25BC, 0x25BE, "TRI_DOWN",  None, None),   # ▼→▾
    (0x2605, 0x2605, "STAR",      None, None),   # ★
]

# Font metrics for each size
METRICS = {
    28: {'ascent': 22, 'descent': 6, 'line_height': 28},
    22: {'ascent': 17, 'descent': 5, 'line_height': 22},
}

def render_glyph(face, cp, pixel_size):
    face.set_pixel_sizes(0, pixel_size)
    flags = freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO
    face.load_char(cp, flags)
    bitmap = face.glyph.bitmap
    w = bitmap.width
    h = bitmap.rows
    xo = face.glyph.bitmap_left
    yo = face.glyph.bitmap_top
    adv = face.glyph.advance.x >> 6

    raw = bytes(bitmap.buffer)
    row_bytes = (w + 7) // 8
    out = bytearray()
    for r in range(h):
        start = r * bitmap.pitch
        out.extend(raw[start:start + row_bytes])
    return w, h, xo, yo, adv, bytes(out)

def main():
    ttf_path = sys.argv[1] if len(sys.argv) > 1 else "/media/sf_share/NF-Mono.ttf"
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(__file__), "..", "main", "symbol_glyphs.h")
    out_path = os.path.abspath(out_path)

    face = freetype.Face(ttf_path)

    with open(out_path, 'w') as f:
        f.write("// Auto-generated by scripts/extract_symbols.py\n")
        f.write("// Symbol glyphs from NF-Mono.ttf (using larger variants)\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")

        f.write("struct SymbolGlyph {\n")
        f.write("    int width;\n")
        f.write("    int height;\n")
        f.write("    int x_off;\n")
        f.write("    int y_off;\n")
        f.write("    int advance;\n")
        f.write("    const uint8_t *bitmap;\n")
        f.write("};\n\n")

        for size in [28, 22]:
            m = METRICS[size]
            f.write(f"// --- {size}pt (ascent={m['ascent']}) ---\n")
            glyphs = []
            for render_cp, target_cp, name, adv28, adv22 in SYMBOLS:
                adv_override = adv28 if size == 28 else adv22
                w, h, xo, yo, adv_orig, bits = render_glyph(face, render_cp, size)
                adv = adv_override if adv_override else adv_orig
                var_name = f"SYM_{name}_{size}_BITS"
                f.write(f"static const uint8_t {var_name}[] = {{\n    ")
                for i, b in enumerate(bits):
                    f.write(f"0x{b:02X},")
                    if (i + 1) % 16 == 0:
                        f.write("\n    ")
                f.write("\n};\n")
                glyphs.append((var_name, target_cp, name, w, h, xo, yo, adv, bits))
                print(f"  {size}pt {name} (render U+{render_cp:04X}→U+{target_cp:04X}): {w}x{h} xo={xo} yo={yo} adv={adv}")

            f.write(f"\nstatic const SymbolGlyph g_symbolGlyphs_{size}[] = {{\n")
            for var_name, target_cp, name, w, h, xo, yo, adv, bits in glyphs:
                f.write(f"    {{ {w}, {h}, {xo}, {yo}, {adv}, {var_name} }},\n")
                f.write(f"    // U+{target_cp:04X} {name}\n")
            f.write("};\n\n")

        f.write("inline const SymbolGlyph *getSymbolGlyph(uint32_t cp, int font_size) {\n")
        f.write("    const SymbolGlyph *table = nullptr;\n")
        f.write("    if (font_size == 28) table = g_symbolGlyphs_28;\n")
        f.write("    if (font_size == 22) table = g_symbolGlyphs_22;\n")
        f.write("    if (!table) table = g_symbolGlyphs_28;\n")
        f.write("    switch (cp) {\n")
        for i, (render_cp, target_cp, name, *_) in enumerate(SYMBOLS):
            f.write(f"        case 0x{target_cp:04X}: return &table[{i}];\n")
        f.write("        default: return nullptr;\n")
        f.write("    }\n")
        f.write("}\n")

    print(f"\nGenerated {out_path}")

if __name__ == '__main__':
    main()
