#!/usr/bin/env python3
"""
Extract symbol glyphs from NF-Mono.ttf at the target font pixel sizes.
Uses larger variants: ▶ (U+25B6) instead of ▸, ▼ (U+25BC) instead of ▾.
"""

import freetype
import sys
import os

# (codepoint_to_render, target_codepoint_in_font, name, advance_override_28, advance_override_22)
# We render the "big" variant but store it under the "small" codepoint for matching
SYMBOLS = [
    (0x25B6, 0x25B8, "TRI_RIGHT", None, None),   # ▶→▸
    (0x25BC, 0x25BE, "TRI_DOWN",  None, None),   # ▼→▾
    (0x2605, 0x2605, "STAR",      None, None),   # ★
    (0x25EF, 0x25CB, "CIRCLE_EMPTY", 28, 22),    # ◯→○ (fullwidth)
    (0x25D0, 0x25D0, "CIRCLE_HALF",  28, 22),    # ◐ (fullwidth)
    (0x2B24, 0x25CF, "CIRCLE_FULL",  28, 22),    # ⬤→● (fullwidth)
    (0xF040, 0x270E, "PENCIL",       None, None),# fa-pen→✎ (Nerd Font icon)
]

# Fullwidth characters missing from 28pt font (present in 22pt)
# These are extracted from SPTICIHAI3.0-Medium_p1.ttf
FULLWIDTH_28 = [
    (0xFF0A, "FW_ASTERISK"),    # ＊
    (0xFF1D, "FW_EQUALS"),      # ＝
    (0xFF3F, "FW_UNDERSCORE"),  # ＿
    (0xFF41, "FW_a"),           # ａ
    (0xFF43, "FW_c"),           # ｃ
    (0xFF45, "FW_e"),           # ｅ
    (0xFF47, "FW_g"),           # ｇ
    (0xFF4D, "FW_m"),           # ｍ
    (0xFF4E, "FW_n"),           # ｎ
    (0xFF4F, "FW_o"),           # ｏ
    (0xFF50, "FW_p"),           # ｐ
    (0xFF51, "FW_q"),           # ｑ
    (0xFF52, "FW_r"),           # ｒ
    (0xFF53, "FW_s"),           # ｓ
    (0xFF55, "FW_u"),           # ｕ
    (0xFF56, "FW_v"),           # ｖ
    (0xFF57, "FW_w"),           # ｗ
    (0xFF58, "FW_x"),           # ｘ
    (0xFF59, "FW_y"),           # ｙ
    (0xFF5A, "FW_z"),           # ｚ
    (0xFF5F, "FW_RPAREN"),      # 〛
]

# Characters missing from 22pt font
FULLWIDTH_22 = [
    (0x3000, "FW_IDEO_SPACE"),  # 全角空格
]

# Font metrics for each size
METRICS = {
    28: {'ascent': 22, 'descent': 6, 'line_height': 28},
    22: {'ascent': 17, 'descent': 5, 'line_height': 22},
}

def render_glyph(face, cp, pixel_size):
    face.set_pixel_sizes(0, pixel_size)
    flags = freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO
    face.load_char(cp, flags)
    bitmap = face.glyph.bitmap
    w = bitmap.width
    h = bitmap.rows
    xo = face.glyph.bitmap_left
    yo = face.glyph.bitmap_top
    adv = face.glyph.advance.x >> 6

    raw = bytes(bitmap.buffer)
    row_bytes = (w + 7) // 8
    out = bytearray()
    for r in range(h):
        start = r * bitmap.pitch
        out.extend(raw[start:start + row_bytes])
    return w, h, xo, yo, adv, bytes(out)

def main():
    ttf_path = sys.argv[1] if len(sys.argv) > 1 else "/media/sf_share/NF-Mono.ttf"
    fw_ttf_path = sys.argv[2] if len(sys.argv) > 2 else "/media/sf_share/SPTICIHAI3.0-Medium_p1.ttf"
    out_path = sys.argv[3] if len(sys.argv) > 3 else os.path.join(
        os.path.dirname(__file__), "..", "main", "symbol_glyphs.h")
    out_path = os.path.abspath(out_path)

    face = freetype.Face(ttf_path)
    fw_face = freetype.Face(fw_ttf_path)

    # Build per-size supplement lists
    FW_SUPPLEMENT = {
        28: [(cp, name) for cp, name in FULLWIDTH_28],
        22: [(cp, name) for cp, name in FULLWIDTH_22],
    }

    with open(out_path, 'w') as f:
        f.write("// Auto-generated by scripts/extract_symbols.py\n")
        f.write("// Symbol glyphs from NF-Mono.ttf + SPTICIHAI3.0-Medium_p1.ttf\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")

        f.write("struct SymbolGlyph {\n")
        f.write("    int width;\n")
        f.write("    int height;\n")
        f.write("    int x_off;\n")
        f.write("    int y_off;\n")
        f.write("    int advance;\n")
        f.write("    const uint8_t *bitmap;\n")
        f.write("};\n\n")

        # Collect all (target_cp, name) across sizes for getSymbolGlyph
        all_target_cps = [(render_cp, target_cp, name) for render_cp, target_cp, name, *_ in SYMBOLS]

        for size in [28, 22]:
            m = METRICS[size]
            f.write(f"// --- {size}pt (ascent={m['ascent']}) ---\n")
            glyphs = []
            for render_cp, target_cp, name, adv28, adv22 in SYMBOLS:
                adv_override = adv28 if size == 28 else adv22
                if name == "CIRCLE_HALF":
                    # Custom: left half filled + right half outline only
                    # Use full circle, then clear right-half interior (keep edge pixels)
                    w, h, xo, yo, adv_orig, bits_unused = render_glyph(face, 0x2B24, size)
                    w_o, h_o, _, _, _, full_bits = render_glyph(face, 0x2B24, size)
                    adv = adv_override if adv_override else adv_orig
                    # Center the bitmap in the fullwidth advance
                    if adv > w:
                        xo = (adv - w) // 2
                    row_bytes = (w + 7) // 8
                    # Find the visual center of the circle by counting pixels
                    total_pixels = 0
                    weighted_col = 0
                    for r in range(h):
                        for c in range(w):
                            byte_idx = r * row_bytes + c // 8
                            bit = 7 - (c % 8)
                            if (full_bits[byte_idx] >> bit) & 1:
                                total_pixels += 1
                                weighted_col += c
                    center_col = weighted_col / total_pixels if total_pixels > 0 else w / 2
                    # mid_col: first column that belongs to the right half
                    # For visual balance, round up so left half gets slightly more pixels
                    mid_col = int(center_col) + 1
                    half_bits = bytearray(full_bits)
                    # Clear right-half interior pixels (keep only edge pixels)
                    # An edge pixel is one that has at least one transparent neighbor
                    for r in range(h):
                        for c in range(mid_col, w):
                            byte_idx = r * row_bytes + c // 8
                            bit = 7 - (c % 8)
                            is_on = (full_bits[byte_idx] >> bit) & 1
                            if not is_on:
                                continue
                            # Check if this is an edge pixel (has at least one transparent neighbor)
                            is_edge = False
                            for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                                nr, nc = r + dr, c + dc
                                if nr < 0 or nr >= h or nc < 0 or nc >= w:
                                    is_edge = True
                                    break
                                n_byte_idx = nr * row_bytes + nc // 8
                                n_bit = 7 - (nc % 8)
                                if not (full_bits[n_byte_idx] >> n_bit) & 1:
                                    is_edge = True
                                    break
                            if not is_edge:
                                half_bits[byte_idx] &= ~(1 << bit)
                    bits = bytes(half_bits)
                else:
                    w, h, xo, yo, adv_orig, bits = render_glyph(face, render_cp, size)
                    adv = adv_override if adv_override else adv_orig
                    # Center the bitmap in the fullwidth advance
                    if adv > w:
                        xo = (adv - w) // 2
                var_name = f"SYM_{name}_{size}_BITS"
                f.write(f"static const uint8_t {var_name}[] = {{\n    ")
                for i, b in enumerate(bits):
                    f.write(f"0x{b:02X},")
                    if (i + 1) % 16 == 0:
                        f.write("\n    ")
                f.write("\n};\n")
                glyphs.append((var_name, target_cp, name, w, h, xo, yo, adv, bits))
                print(f"  {size}pt {name} (render U+{render_cp:04X}→U+{target_cp:04X}): {w}x{h} xo={xo} yo={yo} adv={adv}")

            # Fullwidth supplement glyphs for this size
            for fw_cp, fw_name in FW_SUPPLEMENT.get(size, []):
                w, h, xo, yo, adv, bits = render_glyph(fw_face, fw_cp, size)
                var_name = f"SYM_{fw_name}_{size}_BITS"
                f.write(f"static const uint8_t {var_name}[] = {{\n    ")
                for i, b in enumerate(bits):
                    f.write(f"0x{b:02X},")
                    if (i + 1) % 16 == 0:
                        f.write("\n    ")
                f.write("\n};\n")
                glyphs.append((var_name, fw_cp, fw_name, w, h, xo, yo, adv, bits))
                print(f"  {size}pt {fw_name} (U+{fw_cp:04X}): {w}x{h} xo={xo} yo={yo} adv={adv}")
                # Track for getSymbolGlyph (only add if not already in all_target_cps)
                if not any(t == fw_cp for _, t, _ in all_target_cps):
                    all_target_cps.append((fw_cp, fw_cp, fw_name))

            f.write(f"\nstatic const SymbolGlyph g_symbolGlyphs_{size}[] = {{\n")
            for var_name, target_cp, name, w, h, xo, yo, adv, bits in glyphs:
                f.write(f"    {{ {w}, {h}, {xo}, {yo}, {adv}, {var_name} }},\n")
                f.write(f"    // U+{target_cp:04X} {name}\n")
            f.write("};\n\n")

        f.write("inline const SymbolGlyph *getSymbolGlyph(uint32_t cp, int font_size) {\n")
        f.write("    const SymbolGlyph *table = nullptr;\n")
        f.write("    if (font_size == 28) table = g_symbolGlyphs_28;\n")
        f.write("    if (font_size == 22) table = g_symbolGlyphs_22;\n")
        f.write("    if (!table) table = g_symbolGlyphs_28;\n")
        f.write("    switch (cp) {\n")
        # Build unified switch: each target_cp maps to its index in the per-size table
        # We need to compute the index for each target_cp per size
        # Since different sizes may have different supplement entries, we need per-size switches
        f.write("    // Common symbols (indices 0-%d)\n" % (len(SYMBOLS) - 1))
        for i, (render_cp, target_cp, name, *_) in enumerate(SYMBOLS):
            f.write(f"        case 0x{target_cp:04X}: return &table[{i}];\n")
        # Size-specific fullwidth supplements
        fw_offset_28 = len(SYMBOLS)
        fw_offset_22 = len(SYMBOLS)
        for fw_cp, fw_name in FULLWIDTH_28:
            idx = fw_offset_28
            fw_offset_28 += 1
            f.write(f"        case 0x{fw_cp:04X}: if (font_size == 28) return &g_symbolGlyphs_28[{idx}]; return nullptr;\n")
        for fw_cp, fw_name in FULLWIDTH_22:
            idx = fw_offset_22
            fw_offset_22 += 1
            f.write(f"        case 0x{fw_cp:04X}: if (font_size == 22) return &g_symbolGlyphs_22[{idx}]; return nullptr;\n")
        f.write("        default: return nullptr;\n")
        f.write("    }\n")
        f.write("}\n")

    print(f"\nGenerated {out_path}")

if __name__ == '__main__':
    main()
